### ISSUE TITLE
There's programs that not change to basic style.

### ISSUE THREAD

**Issue by TheLastUmayyad** [arukateru/BasicThemer3#1]
As I said in the title, there's programs that not change, like Regedit or Task manager.
On the second version of BasicThemer, that programs, except Regedit, idk why, change the interface to the basic one.
Thank you for reading, good program :)

**Comment by 7kt4** [comment]
Hi! Thank you! You must run it as administrator for basic theme to be applied to programs that are running as administrator. Programs like regedit/Windows 10 task manager run as administrator!
