### ISSUE TITLE
Since installing ClassicTheme is broken

### ISSUE THREAD

**Issue by that1cutie** [arukateru/BasicThemer3#2]
I understand now that this and classic theme are not designed to be used together. Before realising this, I downloaded this and it messed up my classic theme. Now, even after uninstalling, Windows is stuck in a weird broken metro aero combination and the tools which enable classictheme no longer work. Did BasicThemer3 do something to my system files? If so, some information on what it does to system files would have been nice ahead of time. If this _permanently_ messes with system files, everyone should know this before downloading.

My point is I'm stuck now and I need help, and nobody I know understands a thing about BasicThemer.

**Comment by 7kt4** [comment]
Hi, I am sorry that I didn't reply sooner, I didn't get any notification or anything. No no BasicThemer3 does not touch system files. What do you mean after uninstalling? After removing the scheduled task? Did you figure it out

**Comment by that1cutie** [comment]
I did figure it out, sorry. I forgot to close the topic.
